### ISSUE TITLE
fetch cache ie8

### ISSUE THREAD

**Issue by xiehurricane** [camsong/fetch-ie8#6]
@camsong 
I set {cache:'no-store'} in fetch options,but IE8 always load resource from cache（request param   is the same,but cookie not. It's a new user）.
I want to get resource from server.
Could you help me with this?

**Comment by camsong** [comment]
It uses XMLHttpRequest in IE8 as a polyfill, which can not recognise `{cache:'no-store'}`. The general way to do no cache in IE8 is add a timestamp at the end of url. you may try:

```
fetch('/url' + '?_=' + Date.now())
```

**Comment by xiehurricane** [comment]
@camsong  Thanks
